### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by exoego** [bun913/textlint-rule-aws-service-name#19]
レポジトリのトップページを見ただけではライセンスが分からないため、利用やコントリビューションで少しためらってしまいました。
https://github.com/bun913/textlint-rule-aws-service-name/blob/8bfc3879e1d9e1a428380f6c89e92e4eeba49a67/package.json#L78 を見ると MIT ライセンスと宣言されていますが、package.json を見なければライセンスがわからないのは少々不便に思いました。

[GitHub では LICENSE ファイルを認識して、レポジトリのトップにライセンスを表記](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
)してくれます。
LICENSE ファイルを配置してはいかがでしょうか
![image](https://user-images.githubusercontent.com/127635/223881288-4556c2cd-c7f2-42a1-9624-f5c900cd2bc5.png)

**Comment by bun913** [comment]
@exoego 

ありがとうございます！

Pull Requestも意味のある単位で出していただいていて、勉強しかないです・・・！！

ここについてはおっしゃる通りなので、本日中に対応しておこうと思います！（MITで）

いただいているPRの確認もいたしますね！

**Comment by bun913** [comment]
@exoego 

先にPull Requestを拝見しようと思いましたが、こちらのIssueを先に対応させていただきました！

続けてPull Requestも拝見致しますね！
