### ISSUE TITLE
Is there a way to exclude certain notations?

### ISSUE THREAD

**Issue by watany-dev** [bun913/textlint-rule-aws-service-name#64]
I've been consistently utilizing this fantastic Lint tool, thank you. 

I've run into a challenge lately and wanted to check if there's a feature for it. When there is a specific identifier, like 'some-vpc-0000', it doesn't pass the Lint unless it's 'some-VPC-0000'.

 I'd appreciate it if there's a way to exclude this particular notation. If not, please allow me to assist in implementing this feature.

**Comment by watany-dev** [comment]
Should I proceed with this approach?
https://dev.classmethod.jp/articles/how-to-ignore-in-textlint/

**Comment by exoego** [comment]
You may try https://github.com/textlint/textlint-filter-rule-comments

```markdown
<!-- textlint-disable -->

some-vpc-0000 is ok here

<!-- textlint-enable -->
```

```markdown
<!-- textlint-disable aws-service-name -->

some-vpc-0000 is ok here

<!-- textlint-enableaws-service-name -->

some-vpc-0000 is not ok here
```

**Comment by bun913** [comment]
@watany-dev 

I apologize for the delayed response!

For recurring prefixes, as you've said, they can be ignored with regular expressions!

Also, if you want to locally ignore the rules, as @exoego has mentioned, you can address this by inserting comments within the markdown.

@watany-dev Would either of these methods work for you?

@exoego Thank you as always!

**Comment by bun913** [comment]
Since some time has passed, I am going to close this issue for now.
